language: csharp
dotnet: 2.0.0
os: windows

install:
- cd ./name-sorter
- dotnet restore
- cd ../name-sorter-tests
- dotnet restore
- cd ..

script:
- cd name-sorter
- dotnet build
- dotnet publish -c Release -r win10-x64
- cd ../name-sorter-tests
- dotnet xunit